# site settings
title: Ashley Michelle Thomas
author: ashmictho
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An awesome description.

# social links
twitter_username: thomasashleym
github_username:  ashmictho

# theme
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
